### ISSUE TITLE
Suggestion: Do not mow the grass but leave it "bare/blank/unmowed"

### ISSUE THREAD

**Issue by RundesBalli** [RGBrewer/OpenRCT2-Mow-Grass#2]
I would suggest that you leave the grass unmowed and "bare".

Instead of this:
![grafik](https://user-images.githubusercontent.com/46271553/90982523-d66bc280-e567-11ea-82c5-e06249400294.png)

Use this:
![grafik](https://user-images.githubusercontent.com/46271553/90982531-df5c9400-e567-11ea-9b20-32f6e60ce48f.png)

**Comment by nepumax** [comment]
Yes, that would be so much better!

**Comment by russellbrewer** [comment]
look at line 7 in the javascript file ...

`element.grassLength = 8;`

set that to any number you wish. I dont know which one 'bare' is, might take some experimenting.

**Comment by RundesBalli** [comment]
Ok, i set it to `1` and it works.

Do you want me to create a PR?

**Comment by RundesBalli** [comment]
#3
